<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>2</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>33</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>0.0</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>2767.2841345813185</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>1204.4901354405465</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>523.5258340602123</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1204.4901354405465</CalcMass>
                    <CalcCG>523.5258340602123</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>841.375</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.54</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>294.835008</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, ultra lightweight, 2 mil</Material>
                            <Name>Light HP Parachute [Cd 2.2 (10.4 oz) 34.62 in^3]</Name>
                            <KnownCG>216.94139911067484</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>116.83999999999999</Xb>
                            <CalcMass>284.15198404762236</CalcMass>
                            <CalcCG>216.94139911067484</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>433.8827982213497</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>1</SerialNo>
                            <Dia>3048.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>3048.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>6.56168E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Spectra #200 [Round 1.5 mm, 1/16 in]</ShroudLineMaterial>
                            <DragCoefficient>2.2</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>283.495231</KnownMass>
                            <Density>0.004030444</Density>
                            <Material>Ripstop Nylon, lightweight, 1.3 oz. 4 mil</Material>
                            <Name>SkyAngle Classic 60 [Cd 1.89 (10 oz) 131 in^3]</Name>
                            <KnownCG>355.7298413921081</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>508.0</Xb>
                            <CalcMass>130.2202656318109</CalcMass>
                            <CalcCG>355.7298413921081</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>711.4596827842162</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <Dia>1524.0</Dia>
                            <ShroudLineCount>3</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1524.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.012401366</ShroudLineMassPerMM>
                            <ShroudLineMaterial>5625 Nylon woven tubular #950 [flat 3/8 x 3/32 in (12.7 x 1.9 mm)]</ShroudLineMaterial>
                            <DragCoefficient>1.89</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>2358.6803240000004</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>45.72</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>152.39999999999998</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>1151.936723342251</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>260.34999999999997</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1151.936723342251</CalcMass>
                    <CalcCG>260.34999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>520.6999999999999</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>147.31999999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>147.31999999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>4535.9237</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>19.049999999999997</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>19.049999999999997</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>400.04999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>292.2474908878186</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>86.35999999999999</Xb>
                            <CalcMass>292.2474908878186</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>147.31999999999996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>2086.5249019999997</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>55.88</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>55.88</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.479999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>113.65180201192948</KnownMass>
                            <Density>1050.0</Density>
                            <Material>ABS - 100% infill</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>113.65180201192948</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>147.31999999999996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>505.7283175648908</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>114.3</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>505.7283175648908</CalcMass>
                    <CalcCG>114.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>228.6</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>147.31999999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>147.31999999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>1360.7771100000002</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>7.619999999999999</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>7.619999999999999</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>277.83911170743744</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>277.83911170743744</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>146.04999999999998</OD>
                            <ID>133.35</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>133.35</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>1818.5832766305007</KnownMass>
                    <Density>7850.0</Density>
                    <Material>Steel</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>6.35</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1818.5832766305007</CalcMass>
                    <CalcCG>6.35</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>12.7</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>0.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>0.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <BodyTube>
                    <KnownMass>10789.87466357523</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>685.7999999999997</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>10789.87466357523</CalcMass>
                    <CalcCG>685.7999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1371.5999999999995</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>13</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>139.7</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>139.7</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>3164.9608028731077</KnownMass>
                            <Density>950.0</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>660.3999999999997</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>38.099999999999994</Xb>
                            <CalcMass>3164.9608028731077</CalcMass>
                            <CalcCG>660.3999999999997</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>1320.7999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>139.3952</OD>
                            <ID>127.35560000000001</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>127.35560000000001</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <MassObject>
                            <KnownMass>3175.1465900000003</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>-154.94</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-154.94</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <FinSet>
                            <KnownMass>1313.282250849599</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>77.51668319762318</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1313.282250849599</CalcMass>
                            <CalcCG>77.51668319762318</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>16</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>147.31999999999996</RootChord>
                            <TipChord>99.06</TipChord>
                            <SemiSpan>152.39999999999998</SemiSpan>
                            <SweepDistance>32.382167724326116</SweepDistance>
                            <Thickness>7.619999999999999</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>48.65999999999999</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>258.12789170165604</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>258.12789170165604</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>139.7</OD>
                            <ID>127.35560000000001</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>127.35560000000001</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts>
                <BodyTube>
                    <KnownMass>393.34424699491535</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>88.89999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>393.34424699491535</CalcMass>
                    <CalcCG>88.89999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>177.79999999999998</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>18</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>147.31999999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>147.31999999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>147.20614355830867</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>147.20614355830867</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>19</SerialNo>
                            <OD>147.31999999999996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>1487.7829735999999</KnownMass>
                            <Density>1050.0</Density>
                            <Material>ABS - 100% infill</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>82.55</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>1176.1812827714957</CalcMass>
                            <CalcCG>82.55</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>165.1</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <OD>147.31999999999996</OD>
                            <ID>114.3</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>114.3</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>561.9203528498781</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>127.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>561.9203528498781</CalcMass>
                    <CalcCG>127.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>254.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>21</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>147.31999999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>147.31999999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>595.33998</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, lightweight, 3 mil</Material>
                            <Name>L3 Elliptical Parachute [Cd 1.55 (21.0 oz) 106.8 in^3]</Name>
                            <KnownCG>103.378</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>58.419999999999995</Xb>
                            <CalcMass>225.8874346911293</CalcMass>
                            <CalcCG>103.378</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>206.756</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <Dia>2108.2000000000003</Dia>
                            <ShroudLineCount>14</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>2453.6399999999994</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.002952756</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon #200 IIa Paraline [flat 4.0 mm, 5/32 in]</ShroudLineMaterial>
                            <DragCoefficient>1.55</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>96.388368</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, ultra lightweight, 2 mil</Material>
                            <Name>Light HP Parachute [Cd 2.2 (3.4 oz) 11.322 in^3]</Name>
                            <KnownCG>758.3296999999886</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>5.08</Xb>
                            <CalcMass>77.03799620390558</CalcMass>
                            <CalcCG>758.3296999999886</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>1516.6593999999773</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>23</SerialNo>
                            <Dia>1524.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1524.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>6.56168E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Spectra #200 [Round 1.5 mm, 1/16 in]</ShroudLineMaterial>
                            <DragCoefficient>2.2</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>907.18474</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>205.73999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>205.73999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>43.17999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>393.34424699491535</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>88.89999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>393.34424699491535</CalcMass>
                    <CalcCG>88.89999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>177.79999999999998</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>25</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>147.31999999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>147.31999999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>907.18474</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>12.7</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>134.61999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>26</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>467.5959854205099</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>5.08</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>467.5959854205099</CalcMass>
                            <CalcCG>5.08</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>10.16</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>27</SerialNo>
                            <OD>147.31999999999996</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>416.7586675611561</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>9.524999999999999</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>416.7586675611561</CalcMass>
                            <CalcCG>9.524999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>19.049999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <OD>146.04999999999998</OD>
                            <ID>133.35</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>133.35</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2727.8749149457512</KnownMass>
                    <Density>7850.0</Density>
                    <Material>Steel</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>9.524999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2727.8749149457512</CalcMass>
                    <CalcCG>9.524999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>19.049999999999997</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>29</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>0.0</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>0.0</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <BodyTube>
                    <KnownMass>10390.249676035406</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>660.3999999999997</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>10390.249676035406</CalcMass>
                    <CalcCG>660.3999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1320.7999999999995</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>30</SerialNo>
                    <OD>152.39999999999998</OD>
                    <ID>139.7</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>139.7</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>2721.5542200000004</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>-165.1</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-165.1</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>31</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <FinSet>
                            <KnownMass>1421.5941890640001</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>86.3304501572292</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1421.5941890640001</CalcMass>
                            <CalcCG>86.3304501572292</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>32</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>167.64</RootChord>
                            <TipChord>86.35999999999999</TipChord>
                            <SemiSpan>160.02</SemiSpan>
                            <SweepDistance>46.260410799766824</SweepDistance>
                            <Thickness>7.619999999999999</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>58.81999999999999</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>3164.9608028731077</KnownMass>
                            <Density>950.0</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>660.3999999999997</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>3164.9608028731077</CalcMass>
                            <CalcCG>660.3999999999997</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>1320.7999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>33</SerialNo>
                            <OD>139.3952</OD>
                            <ID>127.35560000000001</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>127.35560000000001</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
            </Stage2Parts>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>