<?xml version='1.0' encoding='utf-8'?>
<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>2</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>33</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>0.0</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>2440.702624804349</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>1328.8897436925397</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>523.1767224444143</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1328.8897436925397</CalcMass>
                    <CalcCG>523.1767224444143</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>400.31314987667486</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>6</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.54</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>294.835008</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, ultra lightweight, 2 mil</Material>
                            <Name>Light HP Parachute [Cd 2.2 (10.4 oz) 34.62 in^3]</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>116.83999999999999</Xb>
                            <CalcMass>284.15198404762236</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>1</SerialNo>
                            <Dia>3048.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>3048.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>6.56168E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Spectra #200 [Round 1.5 mm, 1/16 in]</ShroudLineMaterial>
                            <DragCoefficient>2.2</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>283.495231</KnownMass>
                            <Density>0.004030444</Density>
                            <Material>Ripstop Nylon, lightweight, 1.3 oz. 4 mil</Material>
                            <Name>SkyAngle Classic 60 [Cd 1.89 (10 oz) 131 in^3]</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>508.0</Xb>
                            <CalcMass>130.2202656318109</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <Dia>1524.0</Dia>
                            <ShroudLineCount>3</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1524.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.012401366</ShroudLineMassPerMM>
                            <ShroudLineMaterial>5625 Nylon woven tubular #950 [flat 3/8 x 3/32 in (12.7 x 1.9 mm)]</ShroudLineMaterial>
                            <DragCoefficient>1.89</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>2358.6803240000004</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>45.72</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>175.64033528067057</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>1269.0828308007808</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>260.34999999999997</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1269.0828308007808</CalcMass>
                    <CalcCG>260.34999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>247.74096822556479</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>162.55999999999997</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>4535.9237</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>19.049999999999997</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>19.049999999999997</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>400.04999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>355.83998890502534</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>86.35999999999999</Xb>
                            <CalcMass>355.83998890502534</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>2086.5249019999997</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>55.88</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>55.88</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.479999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>138.38221790750984</KnownMass>
                            <Density>1050.0</Density>
                            <Material>ABS - 100% infill</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>138.38221790750984</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>557.1583159613181</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>114.3</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>557.1583159613181</CalcMass>
                    <CalcCG>114.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>108.76432751366261</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>162.55999999999997</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>1360.7771100000002</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>7.619999999999999</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>7.619999999999999</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>277.83911170743744</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>277.83911170743744</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.042462639647923</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>133.35</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2182.2999319566006</KnownMass>
                    <Density>7850.0</Density>
                    <Material>Steel</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>6.35</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2182.2999319566006</CalcMass>
                    <CalcCG>6.35</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>6.042462639647923</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>15.240000000000004</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts />
                </BodyTube>
                <BodyTube>
                    <KnownMass>8826.499724792597</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>507.9999999999993</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>8826.499724792597</CalcMass>
                    <CalcCG>507.9999999999993</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>483.3970111718332</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>13</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>154.94</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>2802.6475996143577</KnownMass>
                            <Density>950.0</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>482.5999999999995</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>38.099999999999994</Xb>
                            <CalcMass>2802.6475996143577</CalcMass>
                            <CalcCG>482.5999999999995</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>459.22716061324167</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>155.6004</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                        <MassObject>
                            <KnownMass>3175.1465900000003</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>-154.94</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-154.94</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <FinSet>
                            <KnownMass>1313.2822508495997</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>77.51668319762322</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1313.2822508495997</CalcMass>
                            <CalcCG>77.51668319762322</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>16</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>147.31999999999996</RootChord>
                            <TipChord>99.06</TipChord>
                            <SemiSpan>152.39999999999998</SemiSpan>
                            <SweepDistance>32.382167724326116</SweepDistance>
                            <Thickness>7.619999999999999</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>48.65999999999999</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>258.12789170165604</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>258.12789170165604</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.042462639647923</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>127.35560000000001</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
            <MassObject><Name>AI Ballast</Name><KnownMass>0.0</KnownMass></MassObject></Stage3Parts>
            <Stage2Parts>
                <BodyTube>
                    <KnownMass>433.345356858804</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>88.89999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>433.345356858804</CalcMass>
                    <CalcCG>88.89999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>84.5944769550709</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>18</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>162.55999999999997</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>179.23792033734608</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>179.23792033734608</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>19</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>1487.7829735999999</KnownMass>
                            <Density>1050.0</Density>
                            <Material>ABS - 100% infill</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>82.55</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>1176.1812827714957</CalcMass>
                            <CalcCG>82.55</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>78.552014315423</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>114.3</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>619.0647955125767</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>127.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>619.0647955125767</CalcMass>
                    <CalcCG>127.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>120.84925279295845</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>21</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>162.55999999999997</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>595.33998</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, lightweight, 3 mil</Material>
                            <Name>L3 Elliptical Parachute [Cd 1.55 (21.0 oz) 106.8 in^3]</Name>
                            <KnownCG>103.378</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>58.419999999999995</Xb>
                            <CalcMass>225.8874346911293</CalcMass>
                            <CalcCG>103.378</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>206.756</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <Dia>2108.2000000000003</Dia>
                            <ShroudLineCount>14</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>2453.6399999999994</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.002952756</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon #200 IIa Paraline [flat 4.0 mm, 5/32 in]</ShroudLineMaterial>
                            <DragCoefficient>1.55</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>96.388368</KnownMass>
                            <Density>0.0035653924</Density>
                            <Material>Ripstop nylon, ultra lightweight, 2 mil</Material>
                            <Name>Light HP Parachute [Cd 2.2 (3.4 oz) 11.322 in^3]</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>5.08</Xb>
                            <CalcMass>77.03799620390558</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>23</SerialNo>
                            <Dia>1524.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1524.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>6.56168E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Spectra #200 [Round 1.5 mm, 1/16 in]</ShroudLineMaterial>
                            <DragCoefficient>2.2</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>907.18474</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>205.73999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>205.73999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>43.17999999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>433.345356858804</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>88.89999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>433.345356858804</CalcMass>
                    <CalcCG>88.89999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>84.5944769550709</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>25</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>162.55999999999997</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>907.18474</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>12.7</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.7</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>134.61999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>26</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>569.3439822480406</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>5.08</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>569.3439822480406</CalcMass>
                            <CalcCG>5.08</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>10.16</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>27</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>416.7586675611561</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>9.524999999999999</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>416.7586675611561</CalcMass>
                            <CalcCG>9.524999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>9.063693959471882</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>133.35</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>3273.449897934901</KnownMass>
                    <Density>7850.0</Density>
                    <Material>Steel</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>9.524999999999999</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>3273.449897934901</CalcMass>
                    <CalcCG>9.524999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>9.063693959471882</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>29</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>15.240000000000004</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts />
                </BodyTube>
                <BodyTube>
                    <KnownMass>8385.174738552969</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>482.5999999999995</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>8385.174738552969</CalcMass>
                    <CalcCG>482.5999999999995</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>459.22716061324167</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>30</SerialNo>
                    <OD>175.64033528067057</OD>
                    <ID>154.94</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>175.64033528067057</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>2721.5542200000004</KnownMass>
                            <Density>0.0</Density>
                            <Material />
                            <Name>Mass Component</Name>
                            <KnownCG>-165.1</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-165.1</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.39999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>31</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <FinSet>
                            <KnownMass>1421.5941890640001</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>86.3304501572292</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1421.5941890640001</CalcMass>
                            <CalcCG>86.3304501572292</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>32</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>167.64</RootChord>
                            <TipChord>86.35999999999999</TipChord>
                            <SemiSpan>160.02</SemiSpan>
                            <SweepDistance>46.260410799766824</SweepDistance>
                            <Thickness>7.619999999999999</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>58.81999999999999</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>2802.6475996143577</KnownMass>
                            <Density>950.0</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>482.5999999999995</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>2802.6475996143577</CalcMass>
                            <CalcCG>482.5999999999995</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>459.22716061324167</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>33</SerialNo>
                            <OD>175.64033528067057</OD>
                            <ID>155.6004</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>175.64033528067057</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts />
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
            </Stage2Parts>
            <Stage1Parts />
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>